//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEEprjt
{
    using System;
    using System.Collections.Generic;
    
    public partial class lignes
    {
        public string N_DIL { get; set; }
        public string Nature_Ouvrage { get; set; }
        public Nullable<double> Montant_Contractuel { get; set; }
        public string Caractéristiques_ { get; set; }
        public Nullable<double> Distance_km { get; set; }
        public Nullable<double> Avancement { get; set; }
        public string Reference_ouvrage_ { get; set; }
        public string Statut_DI { get; set; }
        public string Contractant { get; set; }
        public string Date_prévisionnelle_mes { get; set; }
        public string Date_référence { get; set; }
        public Nullable<System.DateTime> dbetude { get; set; }
        public Nullable<System.DateTime> dfetudes { get; set; }
        public Nullable<System.DateTime> dbconsultation { get; set; }
        public Nullable<System.DateTime> dfconsultation { get; set; }
        public Nullable<System.DateTime> dbrealisation { get; set; }
        public Nullable<System.DateTime> dfrealisation { get; set; }
        public Nullable<System.DateTime> dbrealiser { get; set; }
        public Nullable<System.DateTime> dfrealiser { get; set; }
    }
}
