//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEEprjt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONEEEntities4 : DbContext
    {
        public ONEEEntities4()
            : base("name=ONEEEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<projet> projet { get; set; }
        public virtual DbSet<poste> poste { get; set; }
        public virtual DbSet<lignes> lignes { get; set; }
        public virtual DbSet<postes> postes { get; set; }
    }
}
