//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEEprjt
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        public string N_DI { get; set; }
        public string Direction { get; set; }
        public string DESIGNATION { get; set; }
        public string Financement { get; set; }
        public string Finalite { get; set; }
        public string FICHE { get; set; }
        public Nullable<double> Montant_DI { get; set; }
        public string region { get; set; }
        public string Observations { get; set; }
        public string annee { get; set; }
    }
}
